apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  labels:
    app: mysql
spec:
  ports:
  - port: {{ .Values.database.port }}
    name: {{ .Values.database.name }}
  clusterIP: None
  selector:
    app: mysql