apiVersion: v1
kind: Service
metadata:
  name: devops-web
spec:
  selector:
    app: devops-web
  ports:
    - protocol: TCP
      port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
  type: LoadBalancer